# Generated by Django 4.2.27 on 2026-02-01 18:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="submissions/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "db_table": "submission_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_column="bid_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supplier_name", models.CharField(max_length=255)),
                (
                    "supplier_tin",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "supplier_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "bid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="RWF", max_length=3)),
                (
                    "technical_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "financial_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_winner", models.BooleanField(default=False)),
                ("is_disqualified", models.BooleanField(default=False)),
                ("disqualification_reason", models.TextField(blank=True, null=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("evaluation_notes", models.TextField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bid",
                "verbose_name_plural": "Bids",
                "db_table": "bids",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("comment", "General Comment"),
                            ("clarification", "Request for Clarification"),
                            ("response", "Response to Clarification"),
                            ("approval", "Approval Note"),
                            ("rejection", "Rejection Reason"),
                        ],
                        default="comment",
                        max_length=20,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "submission_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementCall",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_column="call_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("extended_date", models.DateTimeField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("scope", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Active", "Active"),
                            ("Extended", "Extended"),
                            ("Closed", "Closed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                (
                    "budget_ceiling",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("allow_late_submissions", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Procurement Call",
                "verbose_name_plural": "Procurement Calls",
                "db_table": "procurement_calls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        db_column="submission_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tracking_reference",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("item_description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_of_measure", models.CharField(default="Units", max_length=50)),
                (
                    "estimated_unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                    ),
                ),
                ("justification", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Under Review", "Under Review"),
                            ("Returned", "Returned for Clarification"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Published", "Published to Umucyo"),
                            ("Bidding", "Bidding in Progress"),
                            ("Evaluation", "Under Evaluation"),
                            ("Awarded", "Contract Awarded"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "umucyo_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "call",
                    models.ForeignKey(
                        db_column="call_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="procurement.procurementcall",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "db_table": "submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
