# Generated by Django 4.2.27 on 2026-02-01 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("divisions", "0001_initial"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="current_stage",
            field=models.ForeignKey(
                blank=True,
                db_column="current_stage_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_submissions",
                to="workflows.workflowstage",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="division",
            field=models.ForeignKey(
                db_column="division_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="divisions.division",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procurementcall",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_calls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="procurement.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="procurement.submission",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="evaluated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluated_bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="submission",
            field=models.ForeignKey(
                db_column="submission_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="procurement.submission",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_attachments",
                to="procurement.submission",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_dcc854_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["division", "status"], name="submissions_divisio_23a2d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["call", "status"], name="submissions_call_id_336295_idx"
            ),
        ),
    ]
