# Generated by Django 4.2.27 on 2026-02-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="award_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="umucyo_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
