# Generated by Django 4.2.28 on 2026-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_submission_award_details_submission_umucyo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='cbm_review_deadline',
            field=models.DateField(blank=True, help_text='Deadline for CBM review', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='procurement_deadline',
            field=models.DateField(blank=True, help_text='Expected completion deadline for procurement process', null=True),
        ),
    ]
