# Generated by Django 4.2.28 on 2026-02-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_submission_actual_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Call Issued', 'Call Issued'), ('HOD/DM Submit', 'HOD/DM Submit'), ('Review of Procurement Draft', 'Review of Procurement Draft'), ('Returned', 'Returned for Clarification'), ('CBM Review', 'CBM Review'), ('Publish Plan', 'Publish Plan'), ('Prepare Tender Document', 'Prepare Tender Document'), ('CBM Review TD', 'CBM Review Tender Document'), ('Publication of TD', 'Publication of TD'), ('Bidding', 'Bidding'), ('Evaluation', 'Evaluation'), ('Notify Bidders', 'Notify Bidders'), ('Contract Negotiation', 'Contract Negotiation'), ('Contract Drafting', 'Contract Drafting'), ('Legal Review', 'Legal Review'), ('MINIJUST Legal Review', 'MINIJUST Legal Review'), ('Awarded', 'Awarded'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
    ]
