# Generated by Django 4.2.27 on 2026-02-14 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("procurement", "0006_procurementcall_call_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="number_of_procurement_items",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of procurement items/requests in this submission",
            ),
        ),
        migrations.CreateModel(
            name="SubmissionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="submission_document_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("procurement_plan", "Procurement Plan"),
                            ("technical_specification", "Technical Specification"),
                            ("market_survey", "Market Survey"),
                        ],
                        db_column="document_type",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Maximum file size: 10MB",
                        upload_to="submission_documents/%Y/%m/",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        db_column="submission_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documents",
                        to="procurement.submission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_submission_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Document",
                "verbose_name_plural": "Submission Documents",
                "db_table": "submission_documents",
                "ordering": ["document_type", "-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "document_type"],
                        name="submission__submiss_18410f_idx",
                    )
                ],
            },
        ),
    ]
