# Generated by Django 4.2.28 on 2026-02-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_submission_number_of_procurement_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='bid_validity_extension_used',
            field=models.BooleanField(default=False, help_text='Track if 60-day extension was already used for bid validity period'),
        ),
        migrations.AddField(
            model_name='submission',
            name='current_stage_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for current workflow stage', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='procurement_method',
            field=models.CharField(blank=True, help_text="Selected procurement method (e.g., 'International Competitive', 'National Restricted')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='timeline_last_checked',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last timeline status update', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='timeline_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approaching', 'Approaching Deadline'), ('expired', 'Deadline Expired'), ('none', 'No Timeline')], default='none', help_text='Current timeline status', max_length=20),
        ),
        migrations.CreateModel(
            name='TimelineConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('Publication of TD', 'Publication of Tender Documents'), ('Evaluation', 'Evaluation of Bids/Proposals'), ('Notification', 'Notification to Bidders'), ('Bid Validity Period', 'Bid Validity Period'), ('Contract Signature', 'Contract Signature')], max_length=100)),
                ('procurement_method', models.CharField(blank=True, help_text='Leave blank if timeline applies to all methods', max_length=100, null=True)),
                ('min_days', models.PositiveIntegerField(default=0, help_text='Minimum business days required for this stage')),
                ('max_days', models.PositiveIntegerField(blank=True, help_text='Maximum business days allowed for this stage (if applicable)', null=True)),
                ('is_extendable', models.BooleanField(default=False, help_text='Can this timeline be extended beyond max_days?')),
                ('extension_days', models.PositiveIntegerField(blank=True, help_text='Number of days for single extension', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timeline Configuration',
                'verbose_name_plural': 'Timeline Configurations',
                'db_table': 'timeline_configuration',
                'ordering': ['stage_name', 'procurement_method'],
                'unique_together': {('stage_name', 'procurement_method')},
            },
        ),
    ]
