# Generated by Django 6.0.2 on 2026-02-22 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_add_timeline_fields_and_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Call Issued', 'Call Issued'), ('HOD/DM Submit', 'HOD/DM Submit'), ('Review of Procurement Draft', 'Review of Procurement Draft'), ('Returned', 'Returned for Clarification'), ('Submit Compiled Document', 'Submit Compiled Document'), ('CBM Review', 'CBM Review'), ('Publish Plan', 'Publish Plan'), ('Prepare Tender Document', 'Prepare Tender Document'), ('CBM Review TD', 'CBM Review Tender Document'), ('Publication of TD', 'Publication of TD'), ('Bidding', 'Bidding'), ('Evaluation', 'Evaluation'), ('CBM Approval', 'CBM Approval'), ('Notify Bidders', 'Notify Bidders'), ('Contract Negotiation', 'Contract Negotiation'), ('Contract Drafting', 'Contract Drafting'), ('Legal Review', 'Legal Review'), ('Supplier Approval', 'Supplier Approval'), ('MINIJUST Legal Review', 'MINIJUST Legal Review'), ('Awarded', 'Awarded'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('tender_number', models.CharField(help_text='Tender reference number from Umucyo e-procurement platform', max_length=100, primary_key=True, serialize=False)),
                ('tender_title', models.CharField(help_text='Official title of the tender as registered on Umucyo', max_length=255)),
                ('procurement_method', models.CharField(choices=[('International Competitive', 'International Competitive'), ('International Restricted', 'International Restricted'), ('National Competitive', 'National Competitive'), ('National Restricted', 'National Restricted'), ('Request for Quotations', 'Request for Quotations'), ('National Open Simplified', 'National Open Simplified'), ('National Restricted Simplified', 'National Restricted Simplified'), ('Prequalification', 'Prequalification'), ('Single Source', 'Single Source'), ('Force Account', 'Force Account'), ('Two Stage Tendering', 'Two Stage Tendering'), ('Turnkey', 'Turnkey'), ('Community Participation', 'Community Participation'), ('Competitive Dialogue', 'Competitive Dialogue'), ('Design and Build', 'Design and Build'), ('Pre-financing', 'Pre-financing'), ('Reverse Auctioning', 'Reverse Auctioning')], help_text='Procurement method as defined by RPPA guidelines', max_length=100)),
                ('umucyo_link', models.URLField(blank=True, help_text='Direct link to the tender on Umucyo platform', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenders', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(help_text='The submission this tender was created from', on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='procurement.submission')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'db_table': 'tenders',
                'ordering': ['-created_at'],
            },
        ),
    ]
