# Generated by Django 6.0.2 on 2026-02-22 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_alter_submission_status_tender'),
        ('workflows', '0005_workflowstage_stage_type_alter_workflowstage_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='approval_date',
            field=models.DateField(blank=True, help_text='Latest approval/action date recorded in Umucyo', null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='current_stage',
            field=models.ForeignKey(blank=True, help_text='WorkflowStage entry matching the current tender status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tenders', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Prepare Tender Document', 'Prepare Tender Document'), ('CBM Review TD', 'CBM Review Tender Document'), ('Publication of TD', 'Publication of Tender Document'), ('Bidding', 'Bidding'), ('Evaluation', 'Evaluation'), ('CBM Approval', 'CBM Approval'), ('Notify Bidders', 'Notify Bidders'), ('Contract Negotiation', 'Contract Negotiation'), ('Contract Drafting', 'Contract Drafting'), ('Legal Review', 'Legal Review'), ('Supplier Approval', 'Supplier Approval'), ('MINIJUST Legal Review', 'MINIJUST Legal Review'), ('Awarded', 'Awarded'), ('Completed', 'Completed'), ('Returned', 'Returned for Revision'), ('Cancelled', 'Cancelled')], default='Prepare Tender Document', help_text='Current stage of this individual tender', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Call Issued', 'Call Issued'), ('HOD/DM Submit', 'HOD/DM Submit'), ('Review of Procurement Draft', 'Review of Procurement Draft'), ('Returned', 'Returned for Clarification'), ('Submit Compiled Document', 'Submit Compiled Document'), ('CBM Review', 'CBM Review'), ('Publish Plan', 'Publish Plan'), ('Plan Published', 'Plan Published'), ('Prepare Tender Document', 'Prepare Tender Document'), ('CBM Review TD', 'CBM Review Tender Document'), ('Publication of TD', 'Publication of TD'), ('Bidding', 'Bidding'), ('Evaluation', 'Evaluation'), ('CBM Approval', 'CBM Approval'), ('Notify Bidders', 'Notify Bidders'), ('Contract Negotiation', 'Contract Negotiation'), ('Contract Drafting', 'Contract Drafting'), ('Legal Review', 'Legal Review'), ('Supplier Approval', 'Supplier Approval'), ('MINIJUST Legal Review', 'MINIJUST Legal Review'), ('Awarded', 'Awarded'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='tender',
            name='submission',
            field=models.ForeignKey(help_text='The published plan submission this tender was created from', on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='procurement.submission'),
        ),
        migrations.CreateModel(
            name='TenderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, help_text='Status before the action', max_length=50)),
                ('to_status', models.CharField(help_text='Status after the action', max_length=50)),
                ('action', models.CharField(choices=[('create', 'Created'), ('advance', 'Advanced'), ('return', 'Returned'), ('cancel', 'Cancelled'), ('note', 'Note Added')], default='advance', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approval_date', models.DateField(blank=True, help_text='Umucyo approval date for this action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_actions', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='procurement.tender')),
            ],
            options={
                'db_table': 'tender_history',
                'ordering': ['created_at'],
            },
        ),
    ]
