# Generated by Django 6.0.2 on 2026-02-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_tender_approval_date_tender_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='The published plan submission this tender was created from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='procurement.submission'),
        ),
    ]
