# Generated by Django 6.0.2 on 2026-03-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_tender_submission_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Call Issued', 'Call Issued'), ('HOD/DM Submit', 'HOD/DM Submit'), ('Review of Procurement Draft', 'Review of Procurement Draft'), ('Returned', 'Returned for Clarification'), ('Submit Compiled Document', 'Submit Compiled Document'), ('CBM Review', 'CBM Review'), ('Publish Plan', 'Publish Plan'), ('Plan Published', 'Plan Published'), ('Prepare Tender Document', 'Prepare Tender Document'), ('CBM Review TD', 'CBM Review Tender Document'), ('Publication of TD', 'Publication of TD'), ('Opening', 'Opening'), ('Evaluation', 'Evaluation'), ('CBM Approval', 'CBM Approval'), ('Notify Bidders', 'Notify Bidders'), ('Contract Negotiation', 'Contract Negotiation'), ('Contract Drafting', 'Contract Drafting'), ('Legal Review', 'Legal Review'), ('Supplier Approval', 'Supplier Approval'), ('MINIJUST Legal Review', 'MINIJUST Legal Review'), ('Awarded', 'Awarded'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Prepare Tender Document', 'Prepare Tender Document'), ('CBM Review TD', 'CBM Review Tender Document'), ('Publication of TD', 'Publication of Tender Document'), ('Opening', 'Opening'), ('Evaluation', 'Evaluation'), ('CBM Approval', 'CBM Approval'), ('Notify Bidders', 'Notify Bidders'), ('Contract Negotiation', 'Contract Negotiation'), ('Contract Drafting', 'Contract Drafting'), ('Legal Review', 'Legal Review'), ('Supplier Approval', 'Supplier Approval'), ('MINIJUST Legal Review', 'MINIJUST Legal Review'), ('Awarded', 'Awarded'), ('Completed', 'Completed'), ('Returned', 'Returned for Revision'), ('Cancelled', 'Cancelled')], default='Prepare Tender Document', help_text='Current stage of this individual tender', max_length=50),
        ),
        migrations.CreateModel(
            name='CompiledDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='compiled_documents/')),
                ('status', models.CharField(choices=[('Sent to CBM', 'Sent to CBM'), ('Published', 'Published')], default='Sent to CBM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compiled_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compiled Document',
                'verbose_name_plural': 'Compiled Documents',
                'db_table': 'compiled_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
