# Generated by Django 4.2.27 on 2026-02-01 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="stage_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Call Issued", "Call Issued"),
                            ("Division Submitted", "Division Submitted"),
                            ("Under Review", "Under Review"),
                            ("Approved", "Approved"),
                            ("Published", "Published"),
                            ("Bidding", "Bidding"),
                            ("Evaluation", "Evaluation"),
                            ("Awarded", "Awarded"),
                            ("Completed", "Completed"),
                        ],
                        db_column="stage_name",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(unique=True)),
                ("expected_duration_days", models.PositiveIntegerField(default=7)),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("icon", models.CharField(default="circle", max_length=50)),
                ("is_terminal", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Workflow Stage",
                "verbose_name_plural": "Workflow Stages",
                "db_table": "workflow_stages",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_column="history_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Submitted"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("return", "Returned"),
                            ("publish", "Published"),
                            ("start_bidding", "Bidding Started"),
                            ("evaluate", "Evaluation Started"),
                            ("award", "Awarded"),
                            ("complete", "Completed"),
                            ("cancel", "Cancelled"),
                            ("status_update", "Status Updated"),
                            ("comment", "Comment Added"),
                            ("deadline_extended", "Deadline Extended"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("time_at_previous_stage", models.DurationField(blank=True, null=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        db_column="action_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        db_column="from_stage_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_from",
                        to="workflows.workflowstage",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        db_column="submission_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_history",
                        to="procurement.submission",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        blank=True,
                        db_column="to_stage_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_to",
                        to="workflows.workflowstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow History",
                "verbose_name_plural": "Workflow Histories",
                "db_table": "workflow_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required_approval_roles", models.JSONField(blank=True, default=list)),
                ("minimum_approvals", models.PositiveIntegerField(default=1)),
                (
                    "auto_transition_after_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "escalation_after_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("escalation_roles", models.JSONField(blank=True, default=list)),
                (
                    "allowed_next_stages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="allowed_from_stages",
                        to="workflows.workflowstage",
                    ),
                ),
                (
                    "auto_transition_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_transition_from",
                        to="workflows.workflowstage",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="workflows.workflowstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Configuration",
                "verbose_name_plural": "Workflow Configurations",
                "db_table": "workflow_configurations",
            },
        ),
        migrations.CreateModel(
            name="Deadline",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("is_overdue", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="workflows.workflowstage",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="procurement.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deadline",
                "verbose_name_plural": "Deadlines",
                "db_table": "submission_deadlines",
                "unique_together": {("submission", "stage")},
            },
        ),
    ]
