# Generated by Django 4.2.28 on 2026-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflowstage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowhistory',
            name='approval_date',
            field=models.DateField(blank=True, help_text='Date when this approval occurred in Umucyo (from Publish Plan stage onwards)', null=True),
        ),
    ]
