# Generated by Django 4.2.28 on 2026-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowhistory_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstage',
            name='name',
            field=models.CharField(choices=[('Call Issued', 'Call Issued'), ('HOD/DM Submit', 'HOD/DM Submit'), ('Review of Procurement Draft', 'Review of Procurement Draft'), ('CBM Review', 'CBM Review'), ('Publish Plan', 'Publish Plan'), ('Prepare Tender Document', 'Prepare Tender Document'), ('CBM Review TD', 'CBM Review Tender Document'), ('Publication of TD', 'Publication of TD'), ('Bidding', 'Bidding'), ('Evaluation', 'Evaluation'), ('CBM Approval', 'CBM Approval'), ('Notify Bidders', 'Notify Bidders'), ('Contract Negotiation', 'Contract Negotiation'), ('Contract Drafting', 'Contract Drafting'), ('Legal Review', 'Legal Review'), ('Supplier Approval', 'Supplier Approval'), ('MINIJUST Legal Review', 'MINIJUST Legal Review'), ('Awarded', 'Awarded'), ('Completed', 'Completed')], db_column='stage_name', max_length=50, unique=True),
        ),
    ]
