# Generated by Django 6.0.2 on 2026-02-22 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
        ('procurement', '0011_tender_submission_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=200, unique=True)),
                ('contract_name', models.CharField(max_length=500)),
                ('contract_type', models.CharField(choices=[('Lumpsum', 'Lumpsum'), ('Framework', 'Framework'), ('Consultancy Service', 'Consultancy Service'), ('Works', 'Works')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Renewed', 'Renewed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('completion_certificate_date', models.DateField(blank=True, null=True)),
                ('framework_start_date', models.DateField(blank=True, null=True)),
                ('framework_end_date', models.DateField(blank=True, null=True)),
                ('is_renewed', models.BooleanField(default=False)),
                ('renewal_start_date', models.DateField(blank=True, null=True)),
                ('renewal_end_date', models.DateField(blank=True, null=True)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('kickoff_meeting_date', models.DateField(blank=True, null=True)),
                ('study_review_date', models.DateField(blank=True, null=True)),
                ('works_start_date', models.DateField(blank=True, null=True)),
                ('technical_handover_date', models.DateField(blank=True, null=True)),
                ('provisional_handover_date', models.DateField(blank=True, null=True)),
                ('final_handover_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='divisions.division')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='procurement.tender')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_actions', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='contracts.contract')),
            ],
            options={
                'db_table': 'contract_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('issued_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('completion_certificate_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'contract_purchase_orders',
                'ordering': ['-issued_date'],
            },
        ),
    ]
