# Generated by Django 4.2.27 on 2026-02-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0003_contract_budget_supplier_structure_pm_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="draft_report_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="draft_report_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="final_report_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="final_report_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="inception_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="works_approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ContractComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="contracts.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractMilestoneAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_key",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery Date"),
                            ("framework_expiry", "Framework Expiry"),
                            ("inception", "Inception"),
                            ("draft_report", "Draft Report"),
                            ("final_report", "Final Report"),
                            ("payment", "Payment"),
                            ("kickoff_meeting", "Kickoff Meeting"),
                            ("study_review", "Study Review"),
                            ("works_approval", "Works Approval"),
                            ("works_start", "Work Start"),
                            ("technical_handover", "Technical Handover"),
                            ("provisional_handover", "Provisional Handover"),
                            ("final_handover", "Final Handover"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="Target/deadline date for this milestone."
                    ),
                ),
                (
                    "alert_days_before",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Send alert this many days before target_date.",
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_alerts",
                        to="contracts.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestone_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_milestone_alerts",
                "ordering": ["target_date"],
                "unique_together": {("contract", "milestone_key")},
            },
        ),
    ]
