# Generated by Django 6.0.2 on 2026-02-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contract_consultancy_works_comments_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractcomment",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="contracts.purchaseorder",
            ),
        ),
    ]
