# Generated by Django 6.0.2 on 2026-02-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_contractcomment_add_po_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="performance_guarantee",
            field=models.FileField(
                blank=True, null=True, upload_to="performance_guarantees/contracts/"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="performance_guarantee",
            field=models.FileField(
                blank=True, null=True, upload_to="performance_guarantees/pos/"
            ),
        ),
    ]
