# Generated by Django 6.0.2 on 2026-03-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_pg_received_evaluation_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, help_text='Signed contract document uploaded at contract creation.', null=True, upload_to='contracts/documents/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='document',
            field=models.FileField(blank=True, help_text='PO document uploaded when the purchase order is issued.', null=True, upload_to='purchase_orders/documents/'),
        ),
    ]
