# Generated by Django 6.0.2 on 2026-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_and_po_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='final_handover_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='kickoff_meeting_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_handover_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='study_review_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='technical_handover_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='works_approval_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='works_start_approved',
            field=models.BooleanField(default=False),
        ),
    ]
