# Generated by Django 6.0.2 on 2026-03-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_works_milestone_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='milestone_extension_counts',
            field=models.JSONField(blank=True, default=dict, help_text='Per-milestone extension counts, e.g. {"study_review": 2}.'),
        ),
    ]
