# Generated by Django 4.2.28 on 2026-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_milestone_extension_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_structure',
            field=models.CharField(blank=True, choices=[('Non-consultancy services', 'Non-consultancy services'), ('Framework', 'Framework')], default='', help_text='Non-consultancy services or Framework — the payment structure for Consultancy/Works contracts.', max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Framework', 'Framework'), ('Consultancy Service', 'Consultancy Service'), ('Works', 'Works')], max_length=50),
        ),
    ]
