# Generated by Django 4.2.28 on 2026-03-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_update_contract_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_structure',
            field=models.CharField(blank=True, choices=[('Lumpsum', 'Lumpsum'), ('Framework', 'Framework')], default='', help_text='Lumpsum or Framework — the payment structure for Consultancy/Works contracts.', max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Non-consultancy services', 'Non-consultancy services'), ('Consultancy Service', 'Consultancy Service'), ('Works', 'Works')], max_length=50),
        ),
    ]
