# Generated by Django 4.2.28 on 2026-02-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0004_submission_actual_completion_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('deadline_approaching', 'Deadline Approaching'), ('deadline_missed', 'Deadline Missed'), ('stalled_submission', 'Stalled Submission'), ('long_in_review', 'Long Time in Review'), ('high_priority_stuck', 'High Priority Stuck'), ('budget_threshold', 'Budget Threshold Exceeded')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('days_before_deadline', models.IntegerField(default=7, help_text='Days before deadline to trigger alert')),
                ('days_in_stage', models.IntegerField(default=14, help_text='Days in a stage before triggering stalled alert')),
                ('is_enabled', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_notification', models.BooleanField(default=True)),
                ('notify_division_head', models.BooleanField(default=True)),
                ('notify_cbm', models.BooleanField(default=False)),
                ('notify_procurement_team', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alert Configuration',
                'verbose_name_plural': 'Alert Configurations',
                'db_table': 'alert_configurations',
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=20)),
                ('triggered_reason', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_history', to='procurement.submission')),
            ],
            options={
                'verbose_name': 'Alert History',
                'verbose_name_plural': 'Alert Histories',
                'db_table': 'alert_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='procurement.submission')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission', 'status'], name='alerts_submiss_9ad12a_idx'), models.Index(fields=['status', '-created_at'], name='alerts_status_5c7524_idx'), models.Index(fields=['severity'], name='alerts_severit_362484_idx')],
            },
        ),
    ]
